### ISSUE TITLE
Uncaught BUG: random: addEntropy only supports number, array of numbers or string

### ISSUE THREAD

**Issue by Impulse-LLC** [tildaslash/RatticWeb#403] opened 2015-10-15 11:02 UTC
Good day!

There is error on client-side script which is run after logon to Rattic.

It's found on Chrome 46.0.2490.71 (64-bit).

![2015-10-15 16 00 58](https://cloud.githubusercontent.com/assets/14975179/10511907/047f658e-7356-11e5-91e0-0b407905da7e.png)

All functions are working fine and no other issues I'd found in app.

**Comment by smarthall** [comment] 2015-10-21 23:02
Duplicate of #247

**Closed as completed by smarthall** 2015-10-21 23:02 UTC
