### ISSUE TITLE
Support for other protocol

### ISSUE THREAD

**Issue by Mte90** [tildaslash/RatticWeb#344] opened 2015-03-13 17:15 UTC
Like sftp? is possible add other protocol?
![rattic2](https://cloud.githubusercontent.com/assets/403283/6643489/dc976bfa-c9ac-11e4-9067-3ca2fa296fa8.png)

**Comment by smarthall** [comment] 2015-03-16 12:19
Duplicate of #250

**Closed by smarthall** 2015-03-16 12:19 UTC
